// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
import "../core/AccessControl.sol";
import "../interfaces/IExecutionAuthorization.sol";
import "../interfaces/IFundingEligibilityRegistry.sol";
import "../core/INonceManager.sol";
contract ExecutionAuthorization is AccessControl,IExecutionAuthorization {
    bytes32 public constant EXECUTOR_ROLE=keccak256("EXECUTOR_ROLE"); bytes32 public constant AUTHORIZER_ROLE=keccak256("AUTHORIZER_ROLE");
    mapping(bytes32=>Authorization) private _auth; mapping(bytes32=>bool) public consumed;
    IFundingEligibilityRegistry public immutable eligibilityRegistry; INonceManager public immutable nonceManager;
    event AuthorizationRequested(bytes32 indexed executionId,bytes32 indexed intentHash,bytes32 indexed policyId,bytes32 fundingEligibilityHash,uint256 nonce,uint64 expiresAt,address authorizedSigner,address actor);
    event AuthorizationGranted(bytes32 indexed executionId,bytes32 indexed intentHash,address indexed actor);
    event AuthorizationRevoked(bytes32 indexed executionId,address indexed actor);
    event AuthorizationConsumed(bytes32 indexed executionId,bytes32 indexed intentHash,address indexed executor,address signer,uint256 nonce);
    error Expired(); error AlreadyConsumed(); error InvalidIntent(); error NotApproved(); error InvalidEligibility(); error InvalidSigner(); error InvalidNonce();
    constructor(address admin,address eligibilityRegistryAddress,address nonceManagerAddress) AccessControl(admin){if(eligibilityRegistryAddress==address(0)||nonceManagerAddress==address(0))revert InvalidEligibility();eligibilityRegistry=IFundingEligibilityRegistry(eligibilityRegistryAddress);nonceManager=INonceManager(nonceManagerAddress);}
    function request(bytes32 executionId,bytes32 intentHash,bytes32 policyId,bytes32 fundingEligibilityHash,uint256 nonce,uint64 expiresAt,address authorizedSigner) external onlyRole(AUTHORIZER_ROLE){if(executionId==bytes32(0)||intentHash==bytes32(0)||policyId==bytes32(0)||fundingEligibilityHash==bytes32(0))revert InvalidIntent();if(authorizedSigner==address(0))revert InvalidSigner();if(expiresAt<=block.timestamp)revert Expired();if(consumed[executionId])revert AlreadyConsumed();if(nonceManager.currentNonce(authorizedSigner)!=nonce)revert InvalidNonce();if(!eligibilityRegistry.isEligible(fundingEligibilityHash,executionId,policyId))revert InvalidEligibility();_auth[executionId]=Authorization(executionId,intentHash,policyId,fundingEligibilityHash,nonce,expiresAt,authorizedSigner,false);emit AuthorizationRequested(executionId,intentHash,policyId,fundingEligibilityHash,nonce,expiresAt,authorizedSigner,msg.sender);}
    function grant(bytes32 executionId) external onlyRole(AUTHORIZER_ROLE){Authorization storage a=_auth[executionId];if(a.intentHash==bytes32(0))revert InvalidIntent();if(a.expiresAt<=block.timestamp)revert Expired();if(nonceManager.currentNonce(a.authorizedSigner)!=a.nonce)revert InvalidNonce();if(!eligibilityRegistry.isEligible(a.fundingEligibilityHash,a.executionId,a.policyId))revert InvalidEligibility();a.approved=true;emit AuthorizationGranted(executionId,a.intentHash,msg.sender);}
    function revoke(bytes32 executionId) external onlyRole(AUTHORIZER_ROLE){_auth[executionId].approved=false;emit AuthorizationRevoked(executionId,msg.sender);}
    function consume(bytes32 executionId,bytes32 intentHash) external onlyRole(EXECUTOR_ROLE){if(consumed[executionId])revert AlreadyConsumed();Authorization memory a=_auth[executionId];if(!a.approved)revert NotApproved();if(a.expiresAt<=block.timestamp)revert Expired();if(a.intentHash!=intentHash||intentHash==bytes32(0))revert InvalidIntent();if(nonceManager.currentNonce(a.authorizedSigner)!=a.nonce)revert InvalidNonce();if(!eligibilityRegistry.isEligible(a.fundingEligibilityHash,executionId,a.policyId))revert InvalidEligibility();nonceManager.consumeNonce(a.authorizedSigner,a.nonce);consumed[executionId]=true;emit AuthorizationConsumed(executionId,intentHash,msg.sender,a.authorizedSigner,a.nonce);}
    function authorization(bytes32 executionId) external view returns(Authorization memory){return _auth[executionId];}
    function isAuthorized(bytes32 executionId,bytes32 intentHash,bytes32 policyId,uint256 nonce) external view returns(bool){Authorization memory a=_auth[executionId];return a.approved&&!consumed[executionId]&&a.intentHash==intentHash&&a.policyId==policyId&&a.nonce==nonce&&a.expiresAt>block.timestamp&&nonceManager.currentNonce(a.authorizedSigner)==nonce&&eligibilityRegistry.isEligible(a.fundingEligibilityHash,executionId,policyId);}
    function isAuthorizedFor(bytes32 executionId,bytes32 intentHash,bytes32 policyId,bytes32 fundingEligibilityHash,uint256 nonce,address signer) external view returns(bool){Authorization memory a=_auth[executionId];return a.approved&&!consumed[executionId]&&a.intentHash==intentHash&&a.policyId==policyId&&a.fundingEligibilityHash==fundingEligibilityHash&&a.nonce==nonce&&a.authorizedSigner==signer&&a.expiresAt>block.timestamp&&nonceManager.currentNonce(signer)==nonce&&eligibilityRegistry.isEligible(fundingEligibilityHash,executionId,policyId);}
}
